source 'https://rubygems.org'

gem 'rails', '3.2.9'
gem 'sqlite3'
gem 'json'
gem 'jquery-rails'
gem 'wukong'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end